# ui.properties
# -----------
# Copyright : (c) 2025 - 2026, ZAN DoYe <zandoye@gmail.com>
# Licence   : GPLv2
# 
# This file is a part of smaji cjkv toolbox.


File=File
Hide=Hide
Quit=Quit
Help=Help
About=About
Reset=Reset

Config=Config
Modules=Modules

Info=Info
Contribution=Contribution
License=License

Creator\:=Creator:
Application\ Icons\:=Application Icons:

HiDPI\ UI\ Scale\ (Restart\ to\ apply)=HiDPI UI Scale (Restart to apply)
Auto\ update\ Toolbox=Auto update Toolbox
Update\ Toolbox\ now=Update Toolbox now
Auto\ update\ modules=Auto update modules
Update\ modules\ now=Update modules now
Check\ for\ updates\ every\:=Check for updates every:
Launch\ on\ startup=Launch on startup
Start\ minimized=Start minimized
Check\ now=Check now

Reset=Reset
resetInfo=\
  <b><font color="red">RESET</font> Toolbox</b>\
  <br/>\
  All modules will be <font color="red">uninstalled</font><br/>\
  and all footprints will be cleaned up(config files or entries in the registry table)\
  <br/>\
  <br/>\
  After clicking the &lt;Reset&gt; button, resetting will be performed and this toolbox will quit.<br/>\
  <br/>\
  A fresh beginning by starting this toolbox again,<br/>\
  Or purge this software completely,<br/>\
  by removing the directory containing this software:<br/>

Name=Name
Description=Description
Status=Status
Latest=Latest

Uninstalled=Uninstalled
Installed=Installed
Uninstalling=Uninstalling
Installing=Installing
Broken=Broken

Update=Update
Install=Install
Setup=Setup
Uninstall=Uninstall

Version\:=Version:
Links\:=Links:

